# docker-compose.yml
services:
  pipeline-part1:
    build: .
    volumes:
      - .:/app
    command: bash run_pipeline_part1.sh

  pipeline-part2:
    build: .
    volumes:
      - .:/app
    command: bash run_pipeline_part2.sh