[mypy]
ignore_missing_imports = True
exclude = (7_plot_regressions|3_sync_shift_to_uwb)

[mypy-pandas.*]
ignore_errors = True

[mypy-numpy.*]
ignore_errors = True

[mypy-matplotlib.*]
ignore_errors = True

[mypy-sklearn.*]
ignore_errors = True

[mypy-scipy.*]
ignore_errors = True

[mypy-thesis_work.7_plot_regressions]
ignore_errors = True

[mypy-thesis_work.3_sync_shift_to_uwb]
ignore_errors = True
